### ISSUE TITLE
Photos are (generally) too big

### ISSUE THREAD

**Issue by Johngeorgesample** [Johngeorgesample/pgh-coffee#11]
**Issue**
![image](https://github.com/user-attachments/assets/38a45b69-2b0a-489c-b920-e59c7d4010f5)

The size of these folders is pretty egregious when you consider the only thing these photos are used for is a ~224px header. 

**How to resolve this**
Using https://squoosh.app/, resize each image to something reasonable (750px) and make the quality 75%. No image should be more than 250kb.

**Comment by cgg-cmu** [comment]
Is the intent to optimize what's currently in the project or create an automatic solution. (e.g. processing during build or using the [Image](https://nextjs.org/docs/pages/api-reference/components/image) component? Sounds like crushing the current media right?

Def could knock out a batch conversion if that's all this is looking for now

**Comment by Johngeorgesample** [comment]
That'd be great! You got it, all I want to close this is for the existing images to be resized.

**Comment by Johngeorgesample** [comment]
I'm calling this done. All images are now below 500mb.
