### ISSUE TITLE
[Improvement] Utilize Tailwind Variables for Color Scheme

### ISSUE THREAD

**Issue by Steven-Jarmell** [Johngeorgesample/pgh-coffee#73]
Taking a look through the code, there are no primary/secondary/etc global variables to use for setting background colors. It would be a good (and simple) improvement to add one variable that we can reference so that if we want to change the color we only have to do it in one place.

**Comment by Steven-Jarmell** [comment]
Wanted to create an issue here prior to implementing/making a pull request to we are on the same page 😄

**Comment by Johngeorgesample** [comment]
Thanks for your patience on this! I'm going to stick with the [recommendation from Tailwind to use literal color names](https://tailwindcss.com/docs/customizing-colors#naming-your-colors).
